name: Adapter code coverage
on:
  pull_request:
    paths: ["adapters/*/*.go"]
permissions: 
    pull-requests: write
jobs:
  run-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Get directories
        id: get_directories
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const utils = require('./.github/workflows/helpers/pull-request-utils.js')            
            // consider files that are part of the adapter code
            function filter(filepath) {
              return filepath.startsWith("adapters/") && filepath.split("/").length > 2
            }
            const helper = utils.diffHelper({github, context})
            const files = await helper.getDirectories(filter)
            console.log(JSON.stringify(files))
            return JSON.stringify(files);
        
      - name: Run coverage
        run: |
          directories=$(echo '${{ steps.get_directories.outputs.result }}' | jq -r '.[]')
          go mod download
          
          cd ./adapters
          echo "after cd into adapters directory" + $PWD

          # Iterate through the array
          for directory in "${directories[@]}"; do
            cd $directory
            echo "generate coverage for ${directory} adapter"
            go test -coverprofile="${directory}.out"
            go tool cover -html="${directory}.out" -o "${directory}.html"
            ls
            cd ..            
          done
          


    # - name: Validate
    #   run: |
    #     ./validate.sh --nofmt --cov --race 10
    #   env:
    #     GO111MODULE: "on"
