name: Adapter code coverage
on:
  pull_request_target:
    paths: ["adapters/*/*.go"]
permissions: 
    pull-requests: write
jobs:
  run-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Get changed file directories
        id: get_directories
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const utils = require('./.github/workflows/helpers/pull-request-utils.js')            
            // consider files that are part of the adapter code
            function filter(filepath) {
              return filename.startsWith("adapters/") && filename.split("/").length > 2
            }
            const helper = utils.diffHelper({github, context})
            const files = await helper.getDirectories(filter)
            console.log(files)


    # - name: Validate
    #   run: |
    #     ./validate.sh --nofmt --cov --race 10
    #   env:
    #     GO111MODULE: "on"
